# Generated by Django 4.1.2 on 2022-11-12 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(default='', max_length=200)),
                ('category_image', models.ImageField(default='', upload_to='upload/images/categories')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('length', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=0.0)),
                ('height', models.FloatField(default=0.0)),
                ('product_image', models.ImageField(default='', upload_to='upload/images/products/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='santechnic.category')),
            ],
        ),
    ]
