# Generated by Django 4.1.2 on 2022-11-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('santechnic', '0004_remove_product_height_remove_product_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
